name: Monitor Metrobus CDMX

on:
  schedule:
    - cron: '50 23 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4  # <-- Actualizado a v4

      - name: Configurar Python
        uses: actions/setup-python@v5 # <-- Actualizado a v5
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install -r requirements.txt

      - name: Ejecutar script
        env:
          MI_NUMERO: ${{ secrets.MI_NUMERO }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python alerta_metrobus.py
