name: Monitor Metrobus CDMX

on:
  schedule:
    - cron: '30 10 * * 1-5'
    - cron: '30 22 * * 1-5'
  workflow_dispatch: 

concurrency:
  group: metrobus-bot
  cancel-in-progress: true

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 

    steps:
      - name: Descargar código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: |
          pip install -r requirements.txt

      - name: Ejecutar script de extracción y alertas
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
          USUARIO_API_KEY: ${{ secrets.USUARIO_API_KEY }}
          SENHA_API_KEY: ${{ secrets.SENHA_API_KEY }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: python alerta_metrobus.py

      - name: Guardar Historial en Repositorio
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add historial_metrobus.csv
          
          # Hacemos el commit
          git commit -m "📊 Actualiza historial de datos [skip ci]" || echo "No hay cambios para hacer commit"
          
          # 🛡️ BLINDAJE DE GIT: Descarga y fusiona cambios de último milisegundo antes de empujar
          git pull --rebase origin main
          git push
